// redis
export const REDIS_URL = 'REDIS_URL'

// jwt
export const JWT_SECRET = 'JWT_SECRET'
// jwt过期时间
export const JWT_EXPIRES_IN = 'JWT_EXPIRES_IN'

// model configuration
export const MODEL_CREDENTIAL_ENCRYPTION_KEY = 'MODEL_CREDENTIAL_ENCRYPTION_KEY'

// workflow message queue
export const RABBITMQ_URL = 'RABBITMQ_URL'
export const WORKFLOW_EXECUTOR_ROUTING_MODE = 'WORKFLOW_EXECUTOR_ROUTING_MODE'
export const EXECUTOR_INTERNAL_AUTH_TOKEN = 'EXECUTOR_INTERNAL_AUTH_TOKEN'
export const EXECUTOR_REQUIRE_INTERNAL_AUTH = 'EXECUTOR_REQUIRE_INTERNAL_AUTH'
export const EXECUTOR_ENABLED_CLASSES = 'EXECUTOR_ENABLED_CLASSES'

// plugin artifacts
export const PLUGIN_ARTIFACT_DIRECTORY = 'PLUGIN_ARTIFACT_DIRECTORY'
