// redis
export const REDIS_URL = 'REDIS_URL'

// jwt
export const JWT_SECRET = 'JWT_SECRET'
// jwt过期时间
export const JWT_EXPIRES_IN = 'JWT_EXPIRES_IN'

// model configuration
export const MODEL_CREDENTIAL_ENCRYPTION_KEY = 'MODEL_CREDENTIAL_ENCRYPTION_KEY'

// workflow message queue
export const RABBITMQ_URL = 'RABBITMQ_URL'
export const WORKFLOW_EXECUTOR_ROUTING_MODE = 'WORKFLOW_EXECUTOR_ROUTING_MODE'
export const EXECUTOR_INTERNAL_AUTH_TOKEN = 'EXECUTOR_INTERNAL_AUTH_TOKEN'
export const EXECUTOR_REQUIRE_INTERNAL_AUTH = 'EXECUTOR_REQUIRE_INTERNAL_AUTH'
export const EXECUTOR_ENABLED_CLASSES = 'EXECUTOR_ENABLED_CLASSES'

// plugin artifacts
export const PLUGIN_ARTIFACT_DIRECTORY = 'PLUGIN_ARTIFACT_DIRECTORY'

// knowledge documents
export const KNOWLEDGE_SOURCE_DIRECTORY = 'KNOWLEDGE_SOURCE_DIRECTORY'
export const KNOWLEDGE_SOURCE_STORAGE_DRIVER = 'KNOWLEDGE_SOURCE_STORAGE_DRIVER'
export const KNOWLEDGE_S3_ENDPOINT = 'KNOWLEDGE_S3_ENDPOINT'
export const KNOWLEDGE_S3_REGION = 'KNOWLEDGE_S3_REGION'
export const KNOWLEDGE_S3_BUCKET = 'KNOWLEDGE_S3_BUCKET'
export const KNOWLEDGE_S3_ACCESS_KEY_ID = 'KNOWLEDGE_S3_ACCESS_KEY_ID'
export const KNOWLEDGE_S3_SECRET_ACCESS_KEY = 'KNOWLEDGE_S3_SECRET_ACCESS_KEY'
export const KNOWLEDGE_S3_FORCE_PATH_STYLE = 'KNOWLEDGE_S3_FORCE_PATH_STYLE'
export const KNOWLEDGE_SOURCE_GC_ENABLED = 'KNOWLEDGE_SOURCE_GC_ENABLED'
export const KNOWLEDGE_SOURCE_GC_INTERVAL_MS = 'KNOWLEDGE_SOURCE_GC_INTERVAL_MS'
export const KNOWLEDGE_SOURCE_GC_GRACE_MS = 'KNOWLEDGE_SOURCE_GC_GRACE_MS'
export const KNOWLEDGE_SOURCE_GC_BATCH_SIZE = 'KNOWLEDGE_SOURCE_GC_BATCH_SIZE'

// knowledge search projection
export const OPENSEARCH_URL = 'OPENSEARCH_URL'
export const OPENSEARCH_USERNAME = 'OPENSEARCH_USERNAME'
export const OPENSEARCH_PASSWORD = 'OPENSEARCH_PASSWORD'
export const OPENSEARCH_TLS_REJECT_UNAUTHORIZED = 'OPENSEARCH_TLS_REJECT_UNAUTHORIZED'
